# Python_in_data_science

  I needed erase the past I created in 13 and 14 of september to redo, but this is the same!
