# Python_in_data_science

  precisei apagar a pasta que criei dia 13 e 14 de setembro para refazer, mas essa aqui Ã© a mesma!
